name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    # paths: 
    #  - projects/project2/**

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:

  push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag mainproject:latest --build-arg PROJECT_NAME=project2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbordas/mainproject
          tag_with_ref: true
