
name: Publish Docker image

on:
  push:
    branches: 
      - 'master'
    paths:
      - projects/project2/**
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Run build-tools build command
        uses: buildtool/build-action@v1
        with:
          dockerfile: Dockerfile
          docker-build-args: '--build-arg PROJECT_NAME=Project2'
        
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          repository: bbordas/mainproject:latest
          tag_with_ref: true
