name: Docker

on:
  push:
    branches:
      - master
    # paths: 
    #  - projects/project2/**

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag bbordas/mainproject:latest --build-arg PROJECT_NAME=project2

      - name: Push to Docker Hub
        run: docker push bbordas/mainproject:latest
