# This is a basic workflow to help you get started with Actions

name: Filter Dir

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - '**'
    paths:
#       - projects/project1/**
#       - projects/project2/**
#       - projects/project3/**
#       - package.json
      - tsconfig.json
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check which dir was changed
        shell: bash
        run: |
          ls
          #!/bin/sh
          while inotifywait -e modify /projects/project1; do
            if tail -n1 /projects/project1; then
              echo fuck
            fi
          done

