name: Manual input trigger

on: 
  workflow_dispatch:
    inputs:
      projectName:
        description: 'Project name'     
        required: true
        default: 'project1'
      environment:
        description: 'environment'     
        required: true
        default: 'dev'
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Get Git Version
      uses: docker://gittools/gitversion:5.0.2-beta1-27-linux-centos-7-netcoreapp2.2
      with:
        args: /github/workspace /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_ShortSha > /github/workspace/version.txt\""
      
    - name: Set environment variables
      uses: allenevans/set-env@1.0.0
      with:
        overwrite: false
        PROJECT: ${{ github.event.inputs.projectName }}
        IMAGE: bbordas/mainproject_${{ github.event.inputs.projectName }}
        VERSION: $(cat /home/runner/work/MainProject/MainProject/version.txt) 
        
    - name: printenv
      run: printenv
        
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
        
    - name: Build image
      run: docker build --no-cache --file Dockerfile --tag bbordas/mainproject:latest --tag bbordas/mainproject:$(cat /home/runner/work/MainProject/MainProject/version.txt) --build-arg PROJECT_NAME=$PROJECT .

    - name: Push to Docker Hub
      run: | 
          docker push bbordas/mainproject:$(cat /home/runner/work/MainProject/MainProject/version.txt)
          docker push bbordas/mainproject:latest
          
    - name: display environment
      run: |
        echo ${{ github.event.inputs.projectName }}
        echo ${{ github.event.inputs.environment }}
