name: Manual input trigger

on: 
#   push:
#     branches: master
    
  workflow_dispatch:
    inputs:
      projectName:
        description: 'Project name'     
        required: true
        default: 'project1'
      environment:
        description: 'environment'     
        required: true
        default: 'dev'
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Get Git Version
      uses: docker://gittools/gitversion:5.0.2-beta1-27-linux-centos-7-netcoreapp2.2
      with:
        args: /github/workspace /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_ShortSha > /github/workspace/version.txt\""
        
    - uses: pCYSl5EDgo/cat@master
      id: hello
      with:
        path: /home/runner/work/MainProject/MainProject/version.txt

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
        
#     - name: Build image
#       env:
#         VERSION: ${{ steps.hello.outputs.text }}
#         PROJECT: ${{ github.event.inputs.projectName }}
#         IMAGE: bbordas/mainproject_${{ github.event.inputs.projectName }}
#       run: docker build --no-cache --file Dockerfile --tag $IMAGE:latest --tag $IMAGE:$VERSION --build-arg PROJECT_NAME=$PROJECT .
      
        
#     - name: Push to Docker Hub
#       run: | 
#           docker push bbordas/mainproject_${{ github.event.inputs.projectName }}:$VERSION
#           docker push bbordas/mainproject_${{ github.event.inputs.projectName }}:latest
          
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        build-args: PROJECT_NAME=${{ github.event.inputs.projectName }}
        no-cache: true 
        push: true
        tags: |
            bbordas/mainproject_${{ github.event.inputs.projectName }}:latest
            bbordas/mainproject_${{ github.event.inputs.projectName }}:${{ steps.hello.outputs.text }}
        
